Repository canonical/docker-snap, pull requests merged in 2025-01, with the labels that each got.

#212 Add manual connection command for the home interface
  README.md
Labels: documentation

#215 CI: Run tests on arm runners for Noble and Jammy
  .github/workflows/nvidia-test.yml
  .github/workflows/smoke-test.yml
Labels: CI

#218 ci: skip ci for .md changes
  .github/workflows/smoke-test.yml
Labels: CI

#214 Upgrade to 27.5.0
  snap/snapcraft.yaml
Labels: enhancement

#217 CI: Run Nvidia workflow on UC22
  .github/workflows/nvidia-test.yml
  .github/workflows/testflinger/README.md
  .github/workflows/testflinger/nvidia-job.yaml
  .github/workflows/testflinger/scripts/check-snap-changes.sh
  .github/workflows/testflinger/scripts/setup.sh
  .github/workflows/testflinger/scripts/test.sh
  .github/workflows/testflinger/scripts/wait_for_port.sh
Labels: CI

#220 Upgrade to 27.5.1
  snap/snapcraft.yaml
Labels: enhancement
